name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  build_android:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('android/build.gradle', 'android/app/build.gradle', 'android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Node.js
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12

      - name: Setup Android SDK (API Level 30)
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-30
            ndk-bundle
            build-tools;30.0.3

      - name: Download NDK r17b
        run: |
          curl -o android-ndk-r17b-linux-x86_64.zip https://dl.google.com/android/repository/android-ndk-r17b-linux-x86_64.zip
          unzip android-ndk-r17b-linux-x86_64.zip -d $HOME/android-ndk
          rm android-ndk-r17b-linux-x86_64.zip

      - name: Set NDK path
        run: |
          echo "NDK_HOME=$HOME/android-ndk/android-ndk-r17b" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r17b" >> $GITHUB_ENV
          echo "ndk.dir=$HOME/android-ndk/android-ndk-r17b" > $GITHUB_WORKSPACE/local.properties

      - name: Verify NDK installation
        run: |
          echo "NDK_HOME=$NDK_HOME"
          ls -la $NDK_HOME

      - name: Navigate to Project Root
        run: cd $GITHUB_WORKSPACE
        working-directory: telon-gateway-app

      - name: Install Dependencies
        run: npm install
        working-directory: telon-gateway-app

      - name: Build Android App Bundle
        run: |
          mkdir -p android/app/build/intermediates/assets/release/
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/build/intermediates/assets/release/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release
        working-directory: telon-gateway-app

      - name: Build Android Release
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew bundleRelease -Pkeystore.password=${{ secrets.KEYSTORE_PASSWORD }}
        working-directory: telon-gateway-app

  download_bundle:
    runs-on: ubuntu-latest
    needs: build_android
    steps:
      - name: Download Android App Bundle
        run: |
          mkdir -p $GITHUB_WORKSPACE/dist
          cp $GITHUB_WORKSPACE/android/app/build/outputs/bundle/release/app-release.aab $GITHUB_WORKSPACE/dist
        working-directory: telon-gateway-app

      - name: Archive Bundle
        uses: actions/upload-artifact@v3
        with:
          name: android-bundle
          path: $GITHUB_WORKSPACE/dist
